name: Wechat Dest Version 2

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      download_link:
        description: 'The manual WechatSetup.exe download link'
        required: false
        default: 'https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe'

jobs:
  save_new_wechat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Test Github Action Server Time
      #   run: echo `date`
      - name: Check new version and push
        id: checker
        env: 
          GHTOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash -x ./scripts/destVersionRelease.sh ${{ github.event.inputs.download_link }}
      - name : SET ENV
        run: |
          echo "NEW_VERSION=${{ steps.checker.outputs.NEW_VERSION }}" >> $GITHUB_ENV 
          echo "SKIP_BUILD=${{ steps.checker.outputs.SKIP_BUILD }}" >> $GITHUB_ENV 
  docker_build: 
    needs: save_new_wechat
    if: env.SKIP_BUILD != 'true'
    uses: ./.github/workflows/docker-image-wine-wechat.yml
    with:
      wechat_version: ${{ env.NEW_VERSION }}